export const ADD_ITEM = "ADD_ITEM"
export const REMOVE_ITEM = "REMOVE_ITEM"
export const CLEAR_CART = "CLEAR_CART"
export const DECREMENT_ITEM = "DECREMENT_ITEM"
export const SEND_NEW_ORDER = "SEND_NEW_ORDER"
